name: aws-wandb-k8s
provider:
  name: aws
  account_id: "793009824629"
  region: "eu-central-1"
deployment:
  type: kubernetes
stack:
  - experiment_tracking:
      name: wandb
      params:
        license: "<wandb-licence>"
