name: Install Python dependencies
description: Install all core and optional Python dependencies
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        # Install a specific version of uv.
        version: "0.4.30"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
        cache: "pip"
        cache-dependency-path: |
          uv.lock
    - run: echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
      shell: bash
    - name: Install the project
      run: uv sync --all-extras --dev
      shell: bash
